name: RuboCop

on: [pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.4
      - name: Bundle install
        working-directory: ./hello_world
        run: |
          gem install bundler
          bundle install

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: Check reviewdog version
        run: |
          reviewdog -version

      - name: Run rubocop with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./hello_world
        run: bundle exec rubocop | reviewdog -reporter=github-pr-review -f=rubocop
